import { impactSection } from "./impact.mjs";
import { site } from "../config/site.mjs";
import { consultationPhotos } from "../content/consultation-photos.mjs";
import { consultationRecords } from "../content/consultation-records.mjs";
import { activities } from "../content/activities.mjs";
import { getResource } from "../content/resources.mjs";
import { icon } from "./template.mjs";
import { photoImage } from "./photo.mjs";
import { helpPaths } from "./help-paths.mjs";
import { livingLabFeature } from "./living-lab.mjs";

export function landingPage(programCards) {
  const latestRecords = [
    ...consultationRecords,
    ...activities.filter((item) => item.eventDate).map((item) => ({ ...item, date: item.eventDate, dateLabel: item.eventLabel, area: item.category, followup: [item.description] })),
  ].sort((a, b) => b.date.localeCompare(a.date) || a.href.localeCompare(b.href)).slice(0, 3);
  const guides = ["family-checklist", "shared-living-rules", "consultation-preparation"].map(getResource);
  return `<section class="editorial-hero"><div class="container">
    <div class="editorial-kicker"><p>사람이 있는,<br>지속 가능한 이웃의 삶을 위해</p><span class="editorial-rule" aria-hidden="true"></span><p>오늘도, 더 나은 생활을 함께 생각합니다.</p></div>
    <h1>어르신의 남는 공간과<br>청년의 주거 고민을 잇습니다</h1>
    <div class="editorial-cover"><figure class="editorial-cover-photo">${photoImage(consultationPhotos[0], { eager: true, sizes: "(max-width: 760px) calc(100vw - 40px), (max-width: 1440px) 64vw, 870px" })}<figcaption>지역을 걷고, 이야기를 듣습니다. <span>한지붕의 현장 상담 모습</span></figcaption></figure>
      <div class="editorial-cover-copy"><p class="editorial-note">서울 노원구에서 시작하는<br>주거상생 공익활동</p><p class="cover-intro">한지붕은 서울 노원구를 중심으로 어르신 유휴공간 활용 무료상담, 청년·외국인 유학생 주거문화 안내, 세대공감 프로그램과 주거상생 실태조사를 운영하는 비영리단체입니다.</p><div class="cover-actions"><a class="button" href="/consultation/">어르신 무료상담${icon("arrow")}</a><a class="button button-secondary" href="/resources/#youth-housing">청년 주거정보 보기</a><a class="button button-secondary" href="/activities/">한지붕 활동기록</a></div><p class="cover-footnote">상담과 공익정보를 제공합니다.<br>입주 알선·계약대행은 하지 않습니다.</p></div>
    </div>
  </div></section><section class="guide-home-strip"><div class="container"><div><p class="eyebrow">새로 읽는 주거정보 5편</p><h2>빈방의 가능성부터<br>함께 사는 생활까지</h2></div><div><p>어르신과 청년이 확인할 생활조건, 조사에서 묻는 질문과 세대교류의 의미를 차근차근 읽어보세요.</p><a class="text-link" href="/resources/#housing-reading">새 주거정보 읽기${icon("arrow")}</a><a class="text-link" href="/stories/why-generational-connection/">한지붕이 세대를 잇는 이유${icon("arrow")}</a></div></div></section>${livingLabFeature()}${helpPaths()}${impactSection()}
  <section class="section editorial-process"><div class="container"><div class="section-header"><div><p class="eyebrow">상담 이용방법</p><h2>궁금한 점 하나로<br>시작해도 괜찮습니다.</h2></div><p>한지붕 대표와 운영진이 이야기를 듣고,<br>가족과 다음에 확인할 사항을 함께 정리합니다.</p></div><ol class="steps consultation-steps"><li><span>01</span><h3>간단히 문의하기</h3><p>궁금한 내용과 연락받을 방법을 알려주세요.</p></li><li><span>02</span><h3>함께 확인하기</h3><p>안내 가능한 범위를 설명하고 필요한 질문을 정리합니다.</p></li><li><span>03</span><h3>다음 준비하기</h3><p>관련 생활자료와 추가로 확인할 곳을 안내합니다.</p></li></ol><div class="editorial-process-footer"><p>기초상담은 무료입니다. 집수리·입주 알선·계약대행·법률·세무 자문은 제공하지 않습니다.</p><a class="text-link" href="/programs/senior-home-consulting/">상담 범위 자세히 보기${icon("arrow")}</a></div></div></section>
  <section class="section editorial-stories"><div class="container"><div class="section-header"><div><p class="eyebrow">현장 이야기</p><h2>듣고, 기록하고,<br>다음 상담에 반영합니다.</h2></div><p>어르신과 나눈 질문을 기록하고,<br>가족과 함께 읽는 생활자료로 이어갑니다.</p></div><div class="editorial-story-grid"><figure>${photoImage(consultationPhotos[1])}<figcaption>어르신과 함께 걸으며 이어가는 상담</figcaption></figure><div class="editorial-story-list">${latestRecords.map((activity) => `<article><p class="resource-meta"><time datetime="${activity.date}">${activity.dateLabel}</time> · ${activity.area}</p><h3><a href="${activity.href}">${activity.title}</a></h3><p>${activity.followup[0]}</p><a class="text-link" href="${activity.href}">활동 기록 읽기${icon("arrow")}</a></article>`).join("")}<a class="text-link" href="/activities/field-records/">상담 현장 사진 모두 보기${icon("arrow")}</a></div></div><div class="editorial-related-line"><p>직접 해보고, 다시 해보는 시간.<br>구성원들이 참여해 온 디지털 교육 경험도 소개합니다.</p><a class="text-link" href="/activities/senior-digital-education/">디지털 교육 경험 보기${icon("arrow")}</a></div></div></section>
  <section class="section editorial-guides"><div class="container"><div class="section-header"><div><p class="eyebrow">한지붕 생활자료</p><h2>읽고 끝나는 대신,<br>함께 적어보세요.</h2></div><p>가족회의부터 공동생활의 약속까지.<br>생활 속 질문을 하나씩 정리하는 자료입니다.</p></div><div class="resource-grid">${guides.map((guide, index) => `<article class="resource-card"><span class="editorial-number">0${index + 1}</span><p class="resource-meta">${guide.category} · 읽고 직접 적는 자료</p><h3>${guide.title}</h3><p>${guide.outcome}</p><a class="text-link" href="${guide.href}">자료 읽고 작성하기${icon("arrow")}</a></article>`).join("")}</div><p class="section-action"><a class="button button-secondary" href="/resources/">주거상생 자료 6종 보기${icon("arrow")}</a></p></div></section>
  <section class="section editorial-programs"><div class="container"><div class="section-header"><div><p class="eyebrow">한지붕이 하는 일</p><h2>상담에서 시작해,<br>배움과 조사로 이어갑니다.</h2></div><p>${site.nonprofitDescription}</p></div><div class="program-grid">${programCards()}</div></div></section>
  <section class="section editorial-transparency"><div class="container organization-intro"><div><p class="eyebrow">운영·공개</p><h2>활동과 운영을<br>함께 공개합니다.</h2><p>남는 공간을 살피고,<br>세대가 함께 살아갈 기준을 만듭니다.</p><a class="text-link" href="/about/">한지붕 소개${icon("arrow")}</a></div><div><p>대표 ${site.representative} · 고유번호 ${site.registrationNumber}</p><p>노원구청 마을공동체 사업 지원금 600,000원의 계획과 실제 사용 내역을 구분해 공개합니다.</p><dl class="editorial-funding"><div><dt>실제 집행액</dt><dd>191,500원</dd></div><div><dt>미집행액</dt><dd>408,500원</dd></div></dl><p class="resource-meta">2026년 9월 20일 기준 · 해당 지원금에 한정한 공개</p><a class="text-link" href="/transparency/">단체 운영정보 확인하기${icon("arrow")}</a><br><a class="text-link" href="/activities/nowon-grant-execution/">지원금 계획·집행 현황 보기${icon("arrow")}</a></div></div></section>
  <section class="final-cta"><div class="container"><p class="eyebrow">한지붕 무료상담</p><h2>혼자 결정하기 전에,<br>궁금한 점부터 나눠주세요.</h2><div class="hero-actions"><a class="button" href="/consultation/">무료상담 문의하기${icon("arrow")}</a><a class="button button-secondary" href="${site.phoneHref}">전화로 문의하기</a></div><p class="contact-readable"><a href="${site.phoneHref}">${site.phone}</a><span aria-hidden="true"> · </span><a href="${site.emailHref}">${site.email}</a></p><a class="text-link" href="/partnership/">교육·봉사 기관협력 문의${icon("arrow")}</a></div></section>`;
}
