import { programs, site } from "../config/site.mjs";
import { pageHero, icon } from "../lib/template.mjs";

export const aboutBody = `${pageHero({ eyebrow: "한지붕 소개", title: "어르신의 남는 공간과<br>청년의 주거 고민을 잇습니다", description: "서울 노원구에서 무료상담, 주거문화 안내, 세대교류와 조사를 통해 주거상생의 방법을 찾는 비영리단체입니다." })}
<section class="section"><div class="container content-layout"><article class="prose">
<nav class="field-toc" aria-label="한지붕 소개 목차"><a href="#why">시작한 이유</a><a href="#purpose">설립 목적</a><a href="#programs">주요사업</a><a href="#governance">운영주체</a><a href="#charter">정관과 목적사업</a></nav>
<h2 id="why">한지붕은 왜 시작했나요?</h2><p class="lead">한쪽에는 사용하지 않는 주거공간이 있고, 다른 한쪽에는 높은 주거비를 부담하는 청년들이 있습니다.</p><p>한지붕은 지역의 유휴공간을 활용할 때 필요한 안전과 생활의 기준을 살피고, 세대 간 관계를 연결하는 방법을 연구하고 실천합니다. 공간을 바로 연결하기보다 당사자의 생각과 가족의 걱정부터 듣습니다.</p><p>빈방이 있다는 이유만으로 공동생활을 시작해야 하는 것은 아닙니다. 충분한 정보를 바탕으로 자신의 상황에 맞는 선택을 할 수 있도록 돕는 것이 출발점입니다.</p>
<h2 id="purpose">설립 목적</h2><p>청년의 주거 부담과 고령층의 유휴공간 문제를 함께 바라보고, 서로 다른 세대가 이해하고 협력할 수 있는 주거문화를 만드는 데 기여합니다. 상담과 교육, 지역 활동과 조사를 통해 생활 속에서 필요한 정보를 정리해 공개합니다.</p>
<h3>누구를 위한 활동인가요?</h3><dl class="plain-definitions"><div><dt>어르신</dt><dd>유휴공간 활용과 공동생활 준비, 생활환경에 관한 무료상담과 정보를 제공합니다. 가족도 함께 상담할 수 있습니다.</dd></div><div><dt>청년·외국인 유학생</dt><dd>한국의 주거문화, 공동생활 전에 확인할 안전·생활규칙·공간 사용 기준을 공익자료로 안내합니다. 현재 공개 자료는 한국어로 제공합니다.</dd></div><div><dt>지역기관 · 협력 대상</dt><dd>복지관·경로당·주민센터·학교 등과 상담, 교육과 세대교류 활동을 함께 기획합니다.</dd></div></dl>
<h2 id="programs">주요사업</h2><ul>${programs.map((program) => `<li><a href="${program.href}">${program.title}</a> — ${program.status}</li>`).join("")}</ul><h3>청년·외국인 유학생 주거문화 안내</h3><p>주거공간을 선택할 때 확인할 내용, 개인공간과 공용공간, 생활규칙과 공식 문의처를 안내합니다. 자료는 회원가입이나 문의 없이 무료로 읽을 수 있습니다.</p><a class="text-link" href="/resources/#youth-housing">청년 주거정보 보기</a><p>무료상담은 대표와 운영진이 응대합니다. 교육·봉사는 기관 요청에 따라 협의하며 상설 정규반은 아닙니다. 주거상생 실태조사는 진행 중이고 결과 보고서는 검토 후 공개할 예정입니다.</p><p>부동산 중개·입주 알선·계약대행·안전진단·법률·세무 자문을 제공하거나 수익을 보장하지 않습니다.</p>
<h2 id="governance">설립일과 운영주체</h2><dl class="definition-list"><div><dt>설립·창립총회</dt><dd>2026년 7월 5일 · <a href="/activities/founding-meeting/">창립 기록</a></dd></div><div><dt>고유번호 발급</dt><dd>2026년 7월 9일 · <a href="/activities/nonprofit-registration/">등록 기록</a></dd></div><div><dt>운영주체</dt><dd>한지붕 대표와 운영진</dd></div><div><dt>대표자</dt><dd>${site.representative}</dd></div><div><dt>고유번호</dt><dd>${site.registrationNumber}</dd></div></dl>
<h3>대표자와 의사결정 구조</h3><p>창립총회에서 단체 설립, 대표자 선임, 회칙 승인과 고유사업을 의결했습니다. 대표와 운영진은 상담 응대와 사업별 진행 내용을 확인하며, 주요 사항은 정관과 단체 운영 절차에 따라 결정합니다.</p><p>단체의 법적 지위는 ${site.legalType}입니다. 지원금 사용 계획과 실제 집행은 구분해 공개합니다.</p><a class="text-link" href="/transparency/">운영·투명성 확인하기${icon("arrow")}</a>
<h2 id="charter">정관과 목적사업</h2><p>아래는 정관의 목적사업에 관한 운영진 안내를 알기 쉽게 정리한 요약이며, 정관 원문 인용이나 조문 전문은 아닙니다.</p><ul><li>어르신 빈방·유휴공간 활용 무료상담과 교육·봉사</li><li>청년·외국인 유학생 주거문화와 공동생활 안내</li><li>세대공감·세대교류 프로그램</li><li>주거상생 실태조사, 공익자료·보고서와 정책제안</li></ul><p>국세청 승인자료상 등록 고유사업명은 세대교류 봉사 프로그램, 주거상생 실태조사, 어르신 주택 개선 무료상담입니다. 목적사업 전체와 현재 제공 중인 프로그램의 범위는 구분해 안내합니다.</p><p>정관·등록문서 열람이 필요한 기관은 문의해 주세요. 개인정보와 서명 등을 점검한 공개 가능한 범위로 안내합니다.</p><a class="text-link" href="/contact/">정관·단체정보 문의</a>
<h2>한지붕이 지키는 기준</h2><ol><li>당사자의 선택과 진행하지 않을 권리를 존중합니다.</li><li>생활에서 이해하기 쉬운 정보와 확인할 질문을 제공합니다.</li><li>서로 다른 세대의 생활방식을 존중합니다.</li><li>실제 활동과 계획, 전문기관에 확인할 문제를 구분합니다.</li><li>초기 문의에 민감정보나 상세주소를 요구하지 않습니다.</li></ol>
</article><aside class="side-nav"><h2>도움과 참여</h2><a href="/consultation/">어르신 무료상담</a><a href="/resources/#youth-housing">청년 주거정보</a><a href="/activities/">한지붕 활동기록</a><a href="/partnership/">지역기관 협력</a></aside></div></section>`;
