import { digitalLearning } from "./field-records.mjs";

export const activities = Object.freeze([
  {
    slug: "nowon-grant-execution",
    title: "노원구청 마을공동체 사업 지원금 60만 원의 사용 계획",
    description: "운영자가 정정한 2026년 7~11월 집행 계획을 공개합니다. 총 지원금 600,000원 중 집행 예정액 400,000원, 추후 사업비 200,000원입니다.",
    category: "지원금 사용 계획",
    eventDate: null,
    publishedAt: "2026-09-24",
    publishedLabel: "2026년 9월 24일",
    updatedAt: "2026-09-24",
    author: "한지붕 운영팀",
    href: "/activities/nowon-grant-execution/",
    photo: false,
  },
  {
    slug: "senior-digital-education",
    title: "노원구에서 이어온 시니어 디지털·AI 교육 경험",
    description: "한지붕 구성원들이 노원구에서 참여해 온 스마트폰·디지털 서비스 활용 교육의 내용과 현장 경험을 소개합니다. 교육 기획, 현장 진행과 보조 역할을 맡았습니다.",
    category: "세대교류 교육 경험",
    eventDate: digitalLearning.educationEventDate,
    eventLabel: null,
    publishedAt: "2026-09-23",
    publishedLabel: "2026년 9월 23일",
    updatedAt: "2026-09-23",
    author: "한지붕 운영팀",
    href: "/activities/senior-digital-education/",
    photo: true,
  },
  {
    slug: "nonprofit-registration",
    title: "한지붕의 법인으로 보는 단체 승인과 고유번호 발급",
    description:
      "한지붕의 비영리 목적, 고유번호와 세 가지 고유사업을 확인할 수 있는 운영기록입니다.",
    category: "운영기록",
    publishedAt: "2026-07-09",
    publishedLabel: "2026년 7월 9일",
    updatedAt: "2026-09-23",
    author: "한지붕 운영팀",
    href: "/activities/nonprofit-registration/",
    photo: false,
  },
  {
    slug: "founding-meeting",
    title: "한지붕 창립총회를 개최했습니다",
    description:
      "단체 설립, 대표자 선임, 회칙 승인과 공익 목적사업 의결 내용을 개인정보 없이 정리한 운영기록입니다.",
    category: "단체소식",
    publishedAt: "2026-07-05",
    publishedLabel: "2026년 7월 5일",
    updatedAt: "2026-09-23",
    author: "한지붕 운영팀",
    href: "/activities/founding-meeting/",
    photo: false,
  },
]);
