import { digitalLearning } from "./field-records.mjs";

export const activities = Object.freeze([
{
  slug: "2026-impact", title: "2026 한지붕 활동현황과 연간 목표",
  description: "청년의 주거 부담과 어르신의 유휴공간 문제를 함께 바라보고, 지역 현장에서 상담·조사·세대교류 활동을 이어갑니다. 만나는 사람들, 지역별 활동과 공개자료, 연간 목표를 소개합니다.",
  category: "활동현황", publishedAt: "2026-09-24", publishedLabel: "2026년 9월 24일", updatedAt: "2026-09-24",
  author: "한지붕 운영팀", href: "/activities/2026-impact/", photo: false,
},
{
  "slug": "gongneung-consultation-september",
  "title": "공릉동 어르신 주거상담",
  "eventDate": "2026-09-18",
  "eventLabel": "2026년 9월 18일",
  "paragraphs": [
    "서울 노원구 공릉동에서 지역 어르신을 대상으로 유휴공간 활용과 공동생활에 관한 상담을 진행했습니다.",
    "참여자 11명 · 개별상담 7건 · 추가상담 신청 3건. 추가상담 신청은 상담 완료 건수와 구분합니다.",
    "이날 가장 많이 나온 질문은 전입신고, 다른 사람과 함께 생활할 때의 사생활 문제, 가족의 동의 여부였습니다.",
    "한지붕은 상담에서 나온 질문을 정리해 참여자에게 관련 정보를 추가로 안내하고, 반복되는 질문은 향후 무료 안내자료에 반영하기로 했습니다."
  ],
  "description": "서울 노원구 공릉동에서 지역 어르신을 대상으로 유휴공간 활용과 공동생활에 관한 상담을 진행했습니다.",
  "category": "현장 활동 기록",
  "publishedAt": "2026-09-24",
  "publishedLabel": "2026년 9월 24일",
  "updatedAt": "2026-09-24",
  "author": "한지붕 운영팀",
  "href": "/activities/gongneung-consultation-september/",
  "photo": false
},
{
  "slug": "senior-center-living-consultation",
  "title": "경로당 생활정보 상담",
  "eventDate": "2026-09-11",
  "eventLabel": "2026년 9월 11일",
  "paragraphs": [
    "지역 경로당을 방문해 어르신들과 주거공간 활용과 세대공유에 대한 이야기를 나눴습니다.",
    "참여자 16명 · 생활상담 8건 · 후속안내 5건.",
    "방은 남지만 타인과 함께 사는 것이 걱정된다는 의견이 많이 나왔습니다.",
    "개인공간과 공용공간을 어떻게 구분할 수 있는지, 함께 생활하기 전에 어떤 규칙을 정해야 하는지 중심으로 안내했습니다."
  ],
  "description": "지역 경로당을 방문해 어르신들과 주거공간 활용과 세대공유에 대한 이야기를 나눴습니다.",
  "category": "현장 활동 기록",
  "publishedAt": "2026-09-24",
  "publishedLabel": "2026년 9월 24일",
  "updatedAt": "2026-09-24",
  "author": "한지붕 운영팀",
  "href": "/activities/senior-center-living-consultation/",
  "photo": false
},
{
  "slug": "youth-housing-opinions",
  "title": "청년 주거 의견조사",
  "eventDate": "2026-09-07",
  "eventLabel": "2026년 9월 7일",
  "paragraphs": [
    "노원구에서 생활하거나 학교에 다니는 청년을 대상으로 주거비와 거주형태에 관한 의견을 들었습니다.",
    "참여 청년 24명 · 설문 응답 24건.",
    "월세 부담뿐 아니라 계약기간, 통학시간, 안전, 개인공간 확보 등이 중요한 주거 선택 기준으로 언급됐습니다.",
    "조사 결과는 향후 한지붕의 주거상생 실태조사 자료에 포함할 예정입니다."
  ],
  "description": "노원구에서 생활하거나 학교에 다니는 청년을 대상으로 주거비와 거주형태에 관한 의견을 들었습니다.",
  "category": "현장 활동 기록",
  "publishedAt": "2026-09-24",
  "publishedLabel": "2026년 9월 24일",
  "updatedAt": "2026-09-24",
  "author": "한지붕 운영팀",
  "href": "/activities/youth-housing-opinions/",
  "photo": false
},
  {
    slug: "community-cooperation",
    title: "청년 주거·세대공감 활동 운영을 위한 협력 논의",
    description: "입주 전 생활습관 확인부터 공용공간 이용기준, 생활규칙 사전 합의와 거주 중 불편사항 확인까지 세대공감 활동의 운영 방향을 논의했습니다.",
    category: "협력·운영 논의",
    eventDate: "2026-09-11", eventLabel: "2026년 9월 11일",
    publishedAt: "2026-09-24", publishedLabel: "2026년 9월 24일", updatedAt: "2026-09-24",
    author: "한지붕 운영팀", href: "/activities/community-cooperation/",
    photo: true, image: "community-cooperation.jpg", width: 3024, height: 4032,
    caption: "청년 주거와 세대공감 프로그램의 안정적인 운영을 위한 협력 및 운영방안 논의",
    paragraphs: [
      "한지붕은 청년의 주거 부담과 고령층의 유휴공간 문제를 함께 해결하기 위한 세대공감 활동의 운영 방향을 논의했습니다.",
      "이번 논의에서는 청년이 어르신의 빈방에서 생활할 때 발생할 수 있는 생활 방식의 차이를 줄이기 위해 입주 전 생활습관 확인, 공용공간 이용기준, 생활규칙 사전 합의, 거주 중 불편사항 확인 등의 운영 절차를 구체화했습니다.",
      "또한 청년과 어르신이 서로 안심하고 생활할 수 있도록 지역사회와 협력해 주거정보 제공, 상담, 세대교류 프로그램 등을 지속적으로 확대하는 방안도 함께 검토했습니다.",
      "한지붕은 앞으로도 실제 현장에서 확인되는 의견을 바탕으로 청년과 어르신 모두에게 도움이 되는 세대공감 주거문화를 만들어가겠습니다.",
    ],
  },
  {
    slug: "vacant-room-consultation",
    title: "지역 주민 대상 ‘빈방 활용’ 무료 상담 진행",
    description: "사용하지 않는 방을 가진 어르신들과 빈방의 상태와 활용 가능성을 살펴보고, 공동생활 전에 확인할 생활규칙·공간 분리·주거 안전을 안내했습니다.",
    category: "무료상담 현장",
    eventDate: "2026-08-15", eventLabel: "2026년 8월 15일",
    publishedAt: "2026-09-24", publishedLabel: "2026년 9월 24일", updatedAt: "2026-09-24",
    author: "한지붕 운영팀", href: "/activities/vacant-room-consultation/",
    photo: true, image: "vacant-room-consultation.jpg", width: 1080, height: 1440,
    caption: "지역 주민과 직접 만나 빈방 활용 방법과 세대공감 주거에 대해 안내하는 한지붕 현장 상담",
    photoContext: "사진 속 현수막은 당시 현장의 안내 문구입니다. 현재 한지붕의 무료상담은 빈방 활용에 필요한 기초정보를 안내하며, 임대수익이나 금전 지급을 보장하지 않습니다.",
    paragraphs: [
      "한지붕은 지역 주민을 대상으로 집 안의 사용하지 않는 방을 어떻게 활용할 수 있는지 안내하는 현장 상담을 진행했습니다.",
      "상담에서는 자녀의 독립 이후 남게 된 방을 가진 어르신들을 만나 빈방의 현재 상태와 활용 가능성을 함께 살펴보고, 청년과 함께 생활할 경우 사전에 확인해야 할 생활규칙, 공간 분리, 주거 안전 등에 대해 안내했습니다.",
      "특히 단순히 빈방을 연결하는 것을 넘어, 어르신에게는 유휴공간 활용에 대한 정보를 제공하고 청년에게는 안정적인 주거 선택지를 넓힐 수 있는 방법을 지역 주민들과 함께 고민했습니다.",
      "현장에서 들은 주민들의 질문과 우려사항은 향후 한지붕의 어르신 주거상담 및 세대공감 프로그램을 개선하기 위한 기초자료로 활용할 예정입니다.",
    ],
  },
  {
    slug: "nowon-grant-execution",
    title: "노원구청 마을공동체 사업 지원금 60만 원의 계획과 실제 집행",
    description: "노원구청 마을공동체 사업 지원금 600,000원의 계획과 실제 집행을 구분합니다. 2026년 9월 20일 기준 실제 집행액 191,500원, 지원금 기준 미집행액 408,500원입니다.",
    category: "지원금 계획·집행 기록",
    eventDate: null,
    publishedAt: "2026-09-24",
    publishedLabel: "2026년 9월 24일",
    updatedAt: "2026-09-24",
    author: "한지붕 운영팀",
    href: "/activities/nowon-grant-execution/",
    photo: false,
  },
  {
    slug: "senior-digital-education",
    title: "노원구에서 이어온 시니어 디지털·AI 교육 경험",
    description: "한지붕 구성원들이 노원구에서 참여해 온 스마트폰·디지털 서비스 활용 교육의 내용과 현장 경험을 소개합니다. 교육 기획, 현장 진행과 보조 역할을 맡았습니다.",
    category: "세대교류 교육 경험",
    eventDate: digitalLearning.educationEventDate,
    eventLabel: null,
    publishedAt: "2026-09-23",
    publishedLabel: "2026년 9월 23일",
    updatedAt: "2026-09-23",
    author: "한지붕 운영팀",
    href: "/activities/senior-digital-education/",
    photo: true,
  },
  {
    slug: "nonprofit-registration",
    title: "한지붕의 법인으로 보는 단체 승인과 고유번호 발급",
    description:
      "한지붕의 비영리 목적, 고유번호와 세 가지 고유사업을 확인할 수 있는 운영기록입니다.",
    category: "운영기록",
    publishedAt: "2026-07-09",
    publishedLabel: "2026년 7월 9일",
    updatedAt: "2026-09-23",
    author: "한지붕 운영팀",
    href: "/activities/nonprofit-registration/",
    photo: false,
  },
  {
    slug: "founding-meeting",
    title: "한지붕 창립총회를 개최했습니다",
    description:
      "단체 설립, 대표자 선임, 회칙 승인과 공익 목적사업 의결 내용을 개인정보 없이 정리한 운영기록입니다.",
    category: "단체소식",
    publishedAt: "2026-07-05",
    publishedLabel: "2026년 7월 5일",
    updatedAt: "2026-09-23",
    author: "한지붕 운영팀",
    href: "/activities/founding-meeting/",
    photo: false,
  },
]);
