import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { activities } from "../src/content/activities.mjs";
import { getResource, resources } from "../src/content/resources.mjs";
import { policies, programs, site } from "../src/config/site.mjs";
import { programDetails } from "../src/data/program-details.mjs";
import { absolute, escapeHtml, icon, layout, organizationSchema, pageHero } from "../src/lib/template.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "dist");
const generated = [];

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

const isoDate = (date) => `${date}T00:00:00+09:00`;
const updatedMeta = `<div class="page-meta"><span>마지막 수정일 ${site.updatedAt.replaceAll("-", ".")}</span></div>`;
const cardLink = (href, label) => `<a class="text-link" href="${href}">${escapeHtml(label)}${icon("arrow")}</a>`;

function routeToFile(route) {
  if (route === "/") return path.join(out, "index.html");
  if (route === "/404.html") return path.join(out, "404.html");
  return path.join(out, route.replace(/^\//, ""), "index.html");
}

async function emit(route, html, { indexable = true, updatedAt = site.updatedAt } = {}) {
  const file = routeToFile(route);
  await mkdir(path.dirname(file), { recursive: true });
  const normalized = `${html.replace(/[ \t]+$/gm, "").trimEnd()}\n`;
  await writeFile(file, normalized, "utf8");
  generated.push({ route, file, indexable, updatedAt });
}

function programCards() {
  return [...programs]
    .sort((a, b) => a.order.localeCompare(b.order))
    .map((program) => `<article class="program-card"><span class="program-number">공익사업 ${program.order}</span><h3>${program.title}</h3><p>${program.description}</p>${cardLink(program.href, program.slug === "senior-home-consulting" ? "무료상담 내용 보기" : program.slug === "intergenerational-volunteer" ? "프로그램 알아보기" : "조사와 자료 보기")}</article>`)
    .join("");
}

function resourceCards(items = resources) {
  return items.map((resource) => `<article class="resource-card"><div class="resource-meta"><span>${resource.category}</span><time datetime="${resource.publishedAt}">${resource.publishedLabel}</time><span>${resource.readTime}</span></div><h3>${resource.title}</h3><p>${resource.description}</p>${cardLink(resource.href, "자료 읽기")}</article>`).join("");
}

function activityCards(items = activities) {
  return items.map((activity) => `<article class="activity-card"><div class="resource-meta"><span>${activity.category}</span><time datetime="${activity.publishedAt}">${activity.publishedLabel}</time></div><h3>${activity.title}</h3><p>${activity.description}</p>${cardLink(activity.href, "기록 확인하기")}</article>`).join("");
}

const homeBody = `
  <section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">비영리단체 한지붕</p><h1>남는 공간을 살피고,<br>세대가 함께 살아갈 기준을 만듭니다.</h1><p>${site.nonprofitDescription}</p><div class="hero-actions"><a class="button" href="/resources/">주거상생 자료 보기${icon("arrow")}</a><a class="button button-secondary" href="/programs/senior-home-consulting/">어르신 주택 무료상담</a><a class="button button-text" href="/participate/#partnership">기관 협력 문의</a></div><ul class="trust-list"><li>비영리단체 고유번호 ${site.registrationNumber}</li><li>${site.foundedAtLabel} 결성</li><li>서울 노원구 기반 공익활동</li><li>현재 수익사업 없음</li></ul></div><div class="hero-graphic" aria-label="주택 안의 개인공간과 공용공간을 구분한 추상 도식"><div class="house-diagram" aria-hidden="true"><span class="house-room house-room-a">개인공간</span><span class="house-room house-room-b">공용공간</span><span class="house-room house-room-c">대화와 생활기준</span></div><p class="graphic-caption">공간보다 먼저, 함께 지킬 기준을 살핍니다.</p></div></div></section>
  <section class="section section-muted"><div class="container"><div class="section-header"><div><p class="eyebrow">한지붕의 미션</p><h2>청년의 주거 부담과<br>고령층의 고립을 함께 바라봅니다.</h2></div><p>한지붕은 어르신 주택과 유휴공간을 안전하게 살피고, 세대가 함께 생활하기 전에 필요한 기준과 정보를 제공합니다. 상담, 교육, 조사와 공익자료를 통해 청년의 주거 부담 완화와 고령층의 고립 완화에 기여하고자 합니다.</p></div><div class="problem-grid"><article class="problem-item"><span>01</span><h3>활용되지 못하는 공간</h3><p>어르신 주택과 유휴공간을 살피되 당사자와 가족의 의사를 먼저 확인합니다.</p></article><article class="problem-item"><span>02</span><h3>부족한 주거정보</h3><p>청년과 외국인 유학생이 생활 전에 확인할 주거문화와 생활정보를 정리합니다.</p></article><article class="problem-item"><span>03</span><h3>생활기준과 대화 부족</h3><p>세대가 함께 지내기 전에 공간·시간·소음·방문객 기준을 대화하도록 돕습니다.</p></article></div></div></section>
  <section class="section"><div class="container"><div class="section-header"><div><p class="eyebrow">목적사업</p><h2>한지붕의 세 가지 공익사업</h2></div><p>연결이나 계약보다 먼저 상담·교육·조사를 통해 생활기준과 안전을 확인합니다.</p></div><div class="program-grid">${programCards()}</div></div></section>
  <section class="section section-dark"><div class="container"><div class="section-header"><div><p class="eyebrow">운영 방식</p><h2>연결보다 먼저,<br>생활기준과 안전을 확인합니다.</h2></div><p>실제로 제공하지 않는 진단·공사·전문자문·중개를 약속하지 않고, 확인 가능한 범위를 분명하게 안내합니다.</p></div><ol class="steps"><li><span>1</span><h3>문의 및 정보 확인</h3><p>현재 상황과 궁금한 내용을 최소한의 정보로 확인합니다.</p></li><li><span>2</span><h3>생활과 공간 살펴보기</h3><p>생활패턴, 가족 의견, 개인공간과 공용공간의 기준을 살펴봅니다.</p></li><li><span>3</span><h3>정보와 기준 안내</h3><p>안전, 생활규칙, 갈등 예방과 준비사항을 안내합니다.</p></li><li><span>4</span><h3>활동 후 기록</h3><p>상담·교육·조사 결과를 개인정보가 드러나지 않는 방식으로 정리합니다.</p></li></ol></div></section>
  <section class="section"><div class="container"><div class="section-header"><div><p class="eyebrow">공익정보</p><h2>생활 전에 먼저 확인할<br>주거상생 자료</h2></div><p>가족 대화, 공간 구분, 생활규칙과 갈등 예방을 위해 바로 사용할 수 있는 한지붕의 자체 자료입니다.</p></div><div class="resource-grid">${resourceCards(resources.slice(0, 3))}</div><p>${cardLink("/resources/", "주거상생 자료 전체 보기")}</p></div></section>
  <section class="section section-muted"><div class="container"><div class="section-header"><div><p class="eyebrow">단체소식과 운영기록</p><h2>확인된 사실만 기록합니다.</h2></div><p>현재 공개할 수 있는 내용은 한지붕의 결성과 비영리단체 등록에 관한 기록입니다. 실제 상담·교육·조사 활동은 근거자료가 확인된 뒤 게시합니다.</p></div><div class="activity-grid">${activityCards()}</div><p>${cardLink("/activities/", "활동과 기록 전체 보기")}</p></div></section>
  <section class="section"><div class="container transparency-band"><div><p class="eyebrow">운영·투명성</p><h2>확인할 수 있는 정보로<br>신뢰를 쌓습니다.</h2><p>한지붕은 단체 등록정보, 목적사업, 운영 원칙과 회계 관리 기준을 공개합니다. 단체의 수입과 재산은 공익 목적사업과 운영을 위해 사용하며, 특정 개인에게 이익을 분배하지 않습니다.</p>${cardLink("/transparency/", "운영·투명성 확인하기")}</div><dl class="facts"><div><dt>단체명</dt><dd>${site.name}</dd></div><div><dt>대표자</dt><dd>${site.representative}</dd></div><div><dt>결성일</dt><dd>${site.foundedAtLabel}</dd></div><div><dt>고유번호</dt><dd>${site.registrationNumber}</dd></div><div><dt>소재지</dt><dd>${site.address}</dd></div><div><dt>수익사업</dt><dd>현재 없음</dd></div></dl></div></section>
  <section class="final-cta"><div class="container"><h2>바로 결정하지 않아도 괜찮습니다.</h2><p>어르신 주택의 남는 공간을 어떻게 살필지, 세대가 함께 생활하기 전에 무엇을 확인해야 할지 궁금하다면 먼저 공익자료를 살펴보거나 무료상담을 문의해 주세요.</p><div class="hero-actions"><a class="button" href="/resources/">주거상생 자료 보기</a><a class="button" href="/contact/">무료상담 문의</a><a class="button" href="/participate/#partnership">기관 협력 문의</a></div></div></section>`;

await emit("/", layout({ title: site.name, description: site.nonprofitDescription, path: "/", body: homeBody, jsonLd: [{ "@context": "https://schema.org", "@type": "WebSite", name: site.name, alternateName: site.englishName, url: site.url }, organizationSchema] }));

const aboutBody = `${pageHero({ eyebrow: "한지붕 소개", title: "세대와 공간을 잇는<br>비영리단체, 한지붕", description: "청년의 주거 부담을 덜고 고령층의 고립을 완화하는 지역사회를 만듭니다.", meta: updatedMeta })}<section class="section"><div class="container content-layout"><article class="prose"><h2>남는 공간이 지역의 가능성이 되도록</h2><p class="lead">한지붕의 비전은 남는 공간이 지역의 가능성이 되고, 서로 다른 세대가 안전하게 이웃이 되는 사회를 만드는 것입니다. 공간의 연결만 앞세우지 않고 당사자의 의사, 가족의 합의, 생활규칙과 갈등 예방 정보를 먼저 살핍니다.</p><h2>설립 배경</h2><p>어르신 가정에는 사용하지 않는 방과 유휴공간이 있지만, 이를 어떻게 활용해야 안전한지 판단하기 어렵습니다. 한편 청년과 외국인 유학생은 지역의 주거문화와 계약·생활정보를 충분히 알기 어려울 수 있습니다.</p><p>세대 간에는 기상과 취침 시간, 식사, 청소, 소음, 방문객과 공간 사용에 관한 기준이 다를 수 있습니다. 가족과 당사자의 사전 합의 없이 단순히 사람과 공간을 연결하면 불편과 갈등이 커질 수 있습니다. 그래서 한지붕은 연결보다 상담과 교육, 생활기준을 만드는 대화가 먼저라고 봅니다.</p><h2>운영 원칙</h2><ol><li><strong>공익 목적 우선:</strong> 단체의 수입과 재산은 목적사업과 운영을 위해 사용합니다.</li><li><strong>무료상담과 정보 접근성:</strong> 누구나 이해하기 쉬운 공익자료와 기초상담을 제공합니다.</li><li><strong>개인정보 최소수집:</strong> 주민등록번호·신분증·계좌번호·상세주소를 초기 문의에서 요구하지 않습니다.</li><li><strong>허위·과장 없는 정보:</strong> 확인되지 않은 실적, 보장, 후기와 수치를 게시하지 않습니다.</li><li><strong>세대 간 존중:</strong> 특정 세대를 문제로 규정하지 않고 서로의 생활방식을 이해합니다.</li><li><strong>자율적 결정:</strong> 상담이나 참여 뒤에도 진행하지 않거나 중단할 수 있습니다.</li><li><strong>투명한 관리:</strong> 단체 자금과 개인·영리사업 자금을 구분하고 객관적인 증빙을 보관합니다.</li></ol><h2>운영구조</h2><p>한지붕은 총회, 대표, 운영회의와 회계·감사 절차를 통해 목적사업과 운영사항을 결정합니다. 공개가 확인된 대표자 이외 회원과 운영자의 개인정보는 게시하지 않습니다.</p></article><aside class="side-nav"><h2>함께 보기</h2><a href="/programs/">세 가지 공익사업</a><a href="/transparency/">운영·투명성</a><a href="/activities/">활동과 기록</a><a href="/participate/">참여방법</a></aside></div></section>`;
await emit("/about/", layout({ title: "한지붕 소개", description: "한지붕의 미션, 설립 배경, 운영 원칙과 운영구조를 소개합니다.", path: "/about/", body: aboutBody, breadcrumbs: [{ label: "한지붕 소개", href: "/about/" }], jsonLd: organizationSchema }));

const programsBody = `${pageHero({ eyebrow: "공익사업", title: "상담·교육·조사로 만드는<br>주거상생의 기준", description: "한지붕은 연결과 계약을 앞세우지 않고, 어르신 주택과 세대공존에 필요한 정보와 생활기준을 제공합니다.", meta: updatedMeta })}<section class="section"><div class="container"><div class="program-grid">${programCards()}</div><div class="notice"><h2>한지붕이 하지 않는 일</h2><p>한지붕은 부동산 중개, 입주·계약 보장, 공사와 안전진단, 개별 법률·세무 자문을 제공하지 않습니다. 필요한 경우 관계기관 또는 자격 있는 전문가에게 확인할 수 있도록 구분해 안내합니다.</p></div></div></section>`;
await emit("/programs/", layout({ title: "공익사업", description: "세대교류 봉사 프로그램, 주거상생 실태조사, 어르신 주택 개선 무료상담을 안내합니다.", path: "/programs/", body: programsBody, breadcrumbs: [{ label: "공익사업", href: "/programs/" }] }));

function programPage(program) {
  const detail = programDetails[program.slug];
  const related = detail.resources.map((slug) => getResource(slug)).filter(Boolean);
  const meta = `<div class="page-meta"><span>비용: ${program.slug === "intergenerational-volunteer" ? "개인 봉사 참여 무료·기관 프로그램 별도 확인" : "무료"}</span><span>마지막 수정일 2026.09.23</span></div>`;
  const body = `${pageHero({ eyebrow: detail.eyebrow, title: program.title, description: detail.subtitle, meta })}<section class="section"><div class="container content-layout"><article class="prose"><h2>해결하려는 문제</h2><p class="lead">${detail.problem}</p><div class="program-overview"><section class="info-block"><h2>참여 대상</h2><ul>${detail.targets.map((item) => `<li>${item}</li>`).join("")}</ul></section><section class="info-block"><h2>제공 내용</h2><ul>${detail.provides.map((item) => `<li>${item}</li>`).join("")}</ul></section></div><h2>진행 절차</h2><ol>${detail.steps.map(([title, copy]) => `<li><strong>${title}</strong><br>${copy}</li>`).join("")}</ol><h2>비용과 결정권</h2><p>${detail.cost}</p><h2>하지 않는 업무</h2><ul>${detail.limits.map((item) => `<li>${item}</li>`).join("")}</ul><h2>개인정보와 안전 원칙</h2><p>${detail.privacy}</p><h2>자주 묻는 질문</h2><div class="faq">${detail.faqs.map(([question, answer]) => `<details><summary>${question}</summary><p>${answer}</p></details>`).join("")}</div><section class="related-section"><h2>관련 공익자료</h2><div class="related-grid">${related.map((resource) => `<a class="related-link" href="${resource.href}"><span class="resource-meta">${resource.category} · ${resource.readTime}</span>${resource.title}</a>`).join("")}</div></section></article><aside class="side-nav"><h2>담당 연락처</h2><a href="${site.phoneHref}">${site.phone}</a><a href="${site.emailHref}">${site.email}</a><a href="/contact/">문의 방법 보기</a><a href="/programs/">공익사업 전체 보기</a></aside></div><div class="container contact-strip"><div><h2>${program.title} 문의</h2><p>민감정보나 상세주소 없이 궁금한 내용부터 알려 주세요.</p></div><div class="contact-actions"><a class="button" href="${site.phoneHref}">전화 문의</a><a class="button" href="${site.emailHref}">이메일 문의</a></div></div></section>`;
  return layout({ title: program.title, description: detail.subtitle, path: program.href, body, breadcrumbs: [{ label: "공익사업", href: "/programs/" }, { label: program.title, href: program.href }] });
}

for (const program of programs) await emit(program.href, programPage(program));

const resourcesBody = `${pageHero({ eyebrow: "주거상생 자료", title: "생활 전에 확인할 기준을<br>쉽고 구체적으로 정리했습니다.", description: "가족 대화, 공간 구분, 생활규칙, 갈등 예방과 한국 주거문화에 관한 한지붕의 자체 공익자료입니다.", meta: updatedMeta })}<section class="section"><div class="container"><div class="resource-grid">${resourceCards()}</div></div></section>`;
await emit("/resources/", layout({ title: "주거상생 자료", description: "어르신 주택과 세대공존을 준비하는 가족·청년·기관을 위한 주거상생 공익자료입니다.", path: "/resources/", body: resourcesBody, breadcrumbs: [{ label: "주거상생 자료", href: "/resources/" }] }));

function resourcePage(resource) {
  const related = resource.related.map((slug) => getResource(slug)).filter(Boolean);
  const program = programs.find((item) => item.slug === resource.program);
  const articleSchema = { "@context": "https://schema.org", "@type": "Article", headline: resource.title, description: resource.description, datePublished: resource.publishedAt, dateModified: resource.updatedAt, author: { "@type": "Organization", name: site.name }, publisher: { "@type": "Organization", name: site.name, url: site.url }, mainEntityOfPage: absolute(resource.href) };
  const meta = `<div class="page-meta"><span>${resource.category}</span><span>${resource.readTime}</span><span>작성자 ${resource.author}</span></div>`;
  const body = `${pageHero({ eyebrow: "주거상생 공익자료", title: resource.title, description: resource.description, meta })}<section class="section"><div class="container content-layout"><article class="prose"><div class="article-toolbar"><div><time datetime="${resource.publishedAt}">최초 게시 ${resource.publishedLabel}</time><br><time datetime="${resource.updatedAt}">마지막 수정 ${resource.updatedLabel}</time></div><button class="print-button" type="button" data-print>${icon("print")}인쇄하기</button></div>${resource.content}<section class="related-section"><h2>함께 읽을 자료</h2><div class="related-grid">${related.map((item) => `<a class="related-link" href="${item.href}"><span class="resource-meta">${item.category} · ${item.readTime}</span>${item.title}</a>`).join("")}</div></section></article><aside class="side-nav"><h2>관련 안내</h2><a href="${program.href}">${program.title}</a><a href="/resources/">자료 전체 보기</a><a href="/contact/">전화·이메일 문의</a><p>이 자료는 일반적인 생활정보이며 개별 법률·세무·계약 판단을 대신하지 않습니다.</p></aside></div></section>`;
  return layout({ title: resource.title, description: resource.description, path: resource.href, body, type: "article", publishedAt: isoDate(resource.publishedAt), updatedAt: isoDate(resource.updatedAt), breadcrumbs: [{ label: "주거상생 자료", href: "/resources/" }, { label: resource.title, href: resource.href }], jsonLd: articleSchema, bodyClass: "article-page" });
}
for (const resource of resources) await emit(resource.href, resourcePage(resource), { updatedAt: resource.updatedAt });

const activitiesBody = `${pageHero({ eyebrow: "활동과 기록", title: "성과를 부풀리지 않고,<br>확인된 사실을 기록합니다.", description: "현재는 한지붕의 창립과 비영리단체 등록에 관한 운영기록을 공개합니다. 현장활동은 근거자료가 확인된 뒤 게시합니다.", meta: updatedMeta })}<section class="section"><div class="container record-list">${activities.map((activity) => `<article class="record-item"><time datetime="${activity.publishedAt}">${activity.publishedLabel}</time><div><span class="resource-meta">${activity.category}</span><h2>${activity.title}</h2><p>${activity.description}</p></div>${cardLink(activity.href, "기록 확인")}</article>`).join("")}</div></section>`;
await emit("/activities/", layout({ title: "활동과 기록", description: "한지붕의 창립, 비영리단체 등록과 확인 가능한 공익활동 기록을 공개합니다.", path: "/activities/", body: activitiesBody, breadcrumbs: [{ label: "활동과 기록", href: "/activities/" }] }));

function activityPage(activity) {
  const founding = activity.slug === "founding-meeting";
  const articleBody = founding
    ? `<p class="lead">2026년 7월 5일 한지붕 창립총회를 개최하고 비영리 목적과 운영의 기초를 마련했습니다. 이 글은 개인정보가 포함된 원본 회의자료를 공개하지 않고 확인 가능한 의결 내용만 정리한 운영기록입니다.</p><h2>총회에서 의결한 내용</h2><ul><li>비영리단체 한지붕 설립</li><li>단체명 ‘한지붕’ 의결</li><li>대표자 김현수 선임</li><li>회칙 승인</li><li>세대교류 봉사 프로그램, 주거상생 실태조사, 어르신 주택 개선 무료상담을 고유사업으로 의결</li></ul><h2>공개 범위</h2><p>회원의 전화번호, 생년월일, 주소, 서명과 날인 등 개인을 식별할 수 있는 정보는 공개하지 않습니다. 기관이 단체 등록문서 열람을 요청하는 경우에도 안전한 마스킹본을 준비할 수 있는지 확인한 뒤 대응합니다.</p><h2>창립 이후의 운영 원칙</h2><p>한지붕은 수익사업을 하지 않는 비영리단체로서 목적사업을 중심으로 운영합니다. 확인되지 않은 활동성과, 참여인원과 협력기관을 게시하지 않으며 실제 활동자료가 갖춰진 뒤 기록을 추가합니다.</p>`
    : `<p class="lead">2026년 7월 9일 한지붕은 법인으로 보는 단체 승인을 받고 고유번호 ${site.registrationNumber}을 발급받았습니다. 고유번호 발급은 단체의 세무상 식별과 운영을 위한 절차이며, 개별 사업의 품질이나 안전을 보증하는 표시는 아닙니다.</p><h2>등록정보</h2><dl class="definition-list"><div><dt>단체명</dt><dd>${site.name}</dd></div><div><dt>고유번호</dt><dd>${site.registrationNumber}</dd></div><div><dt>대표자</dt><dd>${site.representative}</dd></div><div><dt>소재지</dt><dd>${site.address}</dd></div><div><dt>수익사업</dt><dd>현재 없음</dd></div></dl><h2>등록한 고유사업</h2><ol><li>세대교류 봉사 프로그램</li><li>주거상생 실태조사</li><li>어르신 주택 개선 무료상담</li></ol><h2>정확한 표현</h2><p>‘법인으로 보는 단체’ 승인은 민법상 법인격 취득과 동일하다고 표현하지 않습니다. 또한 국세청이나 정부기관이 한지붕의 개별 프로그램을 추천하거나 보증한다는 의미도 아닙니다.</p><h2>문서 열람 안내</h2><p>등록문서 원본에는 공개에 적합하지 않은 정보가 포함될 수 있어 웹사이트에서 내려받기를 제공하지 않습니다. 단체 등록문서 열람이 필요한 기관은 <a href="${site.emailHref}">${site.email}</a>으로 문의해 주세요.</p>`;
  const schema = { "@context": "https://schema.org", "@type": "NewsArticle", headline: activity.title, description: activity.description, datePublished: activity.publishedAt, dateModified: activity.updatedAt, author: { "@type": "Organization", name: site.name }, publisher: { "@type": "Organization", name: site.name }, mainEntityOfPage: absolute(activity.href) };
  const body = `${pageHero({ eyebrow: activity.category, title: activity.title, description: activity.description, meta: `<div class="page-meta"><time datetime="${activity.publishedAt}">${activity.publishedLabel}</time><span>작성자 ${activity.author}</span><span>마지막 수정 2026년 9월 23일</span></div>` })}<section class="section"><div class="container content-layout"><article class="prose">${articleBody}</article><aside class="side-nav"><h2>함께 보기</h2><a href="/activities/">활동과 기록</a><a href="/transparency/">운영·투명성</a><a href="/about/">한지붕 소개</a></aside></div></section>`;
  return layout({ title: activity.title, description: activity.description, path: activity.href, body, type: "article", publishedAt: isoDate(activity.publishedAt), updatedAt: isoDate(activity.updatedAt), breadcrumbs: [{ label: "활동과 기록", href: "/activities/" }, { label: activity.title, href: activity.href }], jsonLd: schema });
}
for (const activity of activities) await emit(activity.href, activityPage(activity), { updatedAt: activity.updatedAt });

const transparencyBody = `${pageHero({ eyebrow: "운영·투명성", title: "확인할 수 있는 정보로<br>신뢰를 쌓습니다.", description: "단체 등록정보, 고유사업, 비영리성, 회계·운영 원칙과 공개문서 안내를 확인할 수 있습니다.", meta: updatedMeta })}<section class="section"><div class="container content-layout"><article class="prose"><h2>단체 등록정보</h2><dl class="definition-list"><div><dt>단체명</dt><dd>${site.name} (${site.englishName})</dd></div><div><dt>단체 유형</dt><dd>수익사업을 하지 않는 비영리단체</dd></div><div><dt>고유번호</dt><dd>${site.registrationNumber}</dd></div><div><dt>대표자</dt><dd>${site.representative}</dd></div><div><dt>결성일</dt><dd>${site.foundedAtLabel}</dd></div><div><dt>소재지</dt><dd>${site.address}</dd></div><div><dt>전화</dt><dd><a href="${site.phoneHref}">${site.phone}</a></dd></div><div><dt>이메일</dt><dd><a href="${site.emailHref}">${site.email}</a></dd></div></dl><h2>고유사업</h2><ol><li>세대교류 봉사 프로그램</li><li>주거상생 실태조사</li><li>어르신 주택 개선 무료상담</li></ol><h2>운영과 회계 원칙</h2><ul><li>수입과 재산은 목적사업과 단체 운영을 위해 사용합니다.</li><li>특정 개인에게 단체의 이익을 배분하지 않습니다.</li><li>단체 자금과 개인 또는 영리사업 자금을 혼용하지 않습니다.</li><li>지출은 객관적인 증빙자료와 함께 관리합니다.</li><li>외부 지원금은 정해진 지원 목적에 맞게 사용합니다.</li><li>이해관계가 있는 거래는 내부 절차에 따라 검토합니다.</li><li>개인정보는 활동에 필요한 최소한으로 수집합니다.</li></ul><h2>현재 확인 가능한 재정정보</h2><ul><li>설립 당시 별도 보유재산 없음</li><li>현재 등록상 수익사업 없음</li><li>회계자료는 단체 운영규정과 정관에 따라 관리</li><li>확정된 결산자료가 마련되면 연도별 공개 여부를 검토</li></ul><p>결산이 완료되지 않은 기간의 수입·지출표나 확인되지 않은 재정수치는 게시하지 않습니다.</p><h2>공개문서 안내</h2><p>등록문서 원본에는 개인주소, 서명 등 공개에 적합하지 않은 정보가 포함될 수 있어 웹사이트에서 원본 파일을 제공하지 않습니다. 단체 등록문서 열람이 필요한 기관은 <a href="${site.emailHref}">${site.email}</a>으로 문의해 주세요.</p><h2>비영리단체 자격 확인</h2><p>한지붕은 Google 비영리단체 프로그램의 인증 파트너 Goodstack을 통해 비영리단체 자격 확인을 완료했습니다. 이는 Google이 한지붕의 개별 프로그램, 정보 또는 안전성을 보증한다는 의미가 아닙니다.</p></article><aside class="side-nav"><h2>관련 정보</h2><a href="/activities/nonprofit-registration/">고유번호 발급 기록</a><a href="/about/">설립 목적과 운영 원칙</a><a href="/privacy/">개인정보 처리방침</a><a href="/contact/">문서 열람 문의</a></aside></div></section>`;
await emit("/transparency/", layout({ title: "운영·투명성", description: "한지붕의 등록정보, 고유사업, 비영리성과 회계·운영 원칙을 공개합니다.", path: "/transparency/", body: transparencyBody, breadcrumbs: [{ label: "운영·투명성", href: "/transparency/" }], jsonLd: organizationSchema }));

const participateBody = `${pageHero({ eyebrow: "참여하기", title: "상담·봉사·기관협력으로<br>주거상생에 참여할 수 있습니다.", description: "공익자료를 먼저 살펴본 뒤 전화나 이메일로 필요한 참여방식을 문의해 주세요.", meta: updatedMeta })}<section class="section"><div class="container participation-grid"><article class="participation-card"><span class="program-number">개인·가족</span><h2>어르신·가족 무료상담</h2><p>남는 공간과 생활기준을 어떻게 살필지 궁금한 어르신과 가족이 문의할 수 있습니다.</p><h3>확인하는 정보</h3><p>이름, 연락수단, 시·군·구 수준의 지역, 궁금한 내용만 확인합니다. 상세주소와 민감정보는 보내지 마세요.</p><h3>비용과 답변</h3><p>상담은 무료이며 전화 또는 이메일로 안내합니다. 상담만으로 계약이나 유료서비스가 확정되지 않습니다.</p>${cardLink("/programs/senior-home-consulting/", "무료상담 내용 보기")}</article><article class="participation-card"><span class="program-number">개인 참여</span><h2>세대교류 봉사 참여</h2><p>주거문화와 생활정보, 세대 간 대화에 관심 있는 청년과 시니어가 참여할 수 있습니다.</p><h3>문의 가능한 내용</h3><p>참여 가능한 역할, 필요한 준비, 활동방식과 개인정보 처리범위를 문의할 수 있습니다.</p><h3>비용과 답변</h3><p>개인 봉사 참여에 가입비를 받지 않습니다. 현재 참여 가능한 일정과 역할은 전화 또는 이메일로 확인합니다.</p>${cardLink("/programs/intergenerational-volunteer/", "프로그램 알아보기")}</article><article class="participation-card" id="partnership"><span class="program-number">기관 협력</span><h2>기관 프로그램·조사 협력</h2><p>복지관, 경로당, 주민센터, 대학, 학교와 비영리단체가 교육·봉사·조사를 제안할 수 있습니다.</p><h3>먼저 확인할 내용</h3><p>기관명, 담당자 연락수단, 대상, 목적, 희망 내용과 일정 범위를 확인합니다.</p><h3>비용과 책임</h3><p>기관 프로그램의 비용기준은 확정되어 있지 않습니다. 역할, 비용, 정보관리와 결과 공개범위를 협의한 뒤 진행 여부를 결정합니다.</p>${cardLink("/contact/", "기관 협력 문의하기")}</article></div><div class="container notice"><h2>개인정보 처리 원칙</h2><p>현재 사이트에는 온라인 문의폼이 없습니다. 전화 또는 이메일로 필요한 최소정보만 알려 주세요. 주민등록번호, 신분증, 계좌번호, 상세주소, 건강정보와 가족의 개인정보는 보내지 마세요.</p></div></section>`;
await emit("/participate/", layout({ title: "참여하기", description: "어르신·가족 무료상담, 세대교류 봉사, 기관 프로그램과 조사 협력 방법을 안내합니다.", path: "/participate/", body: participateBody, breadcrumbs: [{ label: "참여하기", href: "/participate/" }] }));

const contactBody = `${pageHero({ eyebrow: "문의", title: "민감정보 없이,<br>궁금한 내용부터 알려 주세요.", description: "현재 한지붕은 안전하게 검증된 온라인 문의 저장기능을 운영하지 않습니다. 전화 또는 실제 대표 이메일로 문의해 주세요.", meta: updatedMeta })}<section class="section"><div class="container"><div class="contact-cards"><article class="contact-card">${icon("phone")}<h2>전화 문의</h2><p>상담, 봉사 참여와 기관협력에 관해 전화로 문의할 수 있습니다. 통화가 연결되지 않으면 이메일로 연락처와 문의유형을 남겨 주세요.</p><a href="${site.phoneHref}">${site.phone}</a></article><article class="contact-card">${icon("mail")}<h2>이메일 문의</h2><p>이름, 연락 가능한 전화 또는 이메일, 시·군·구 수준의 지역, 문의유형과 내용을 적어 주세요. 상세주소와 민감정보는 보내지 마세요.</p><a href="${site.emailHref}">${site.email}</a></article></div><div class="notice"><h2>문의 전에 확인해 주세요</h2><ul><li>전화 또는 이메일 중 하나의 연락수단만 있어도 문의할 수 있습니다.</li><li>주민등록번호, 신분증, 계좌번호, 상세주소, 집 사진은 초기 문의에 필요하지 않습니다.</li><li>상담 신청만으로 계약이나 유료서비스 이용이 확정되지 않습니다.</li><li>방문상담, 기관 프로그램 비용과 답변 가능 시간은 문의 내용에 따라 별도로 확인합니다.</li></ul></div><section class="prose"><h2>문의 유형</h2><ul><li>어르신 주택 개선 무료상담</li><li>세대교류 봉사 참여</li><li>복지관·경로당·주민센터·학교 등 기관협력</li><li>주거상생 자료와 조사 관련 문의</li><li>단체 등록문서 열람 문의</li><li>개인정보 열람·정정·삭제 요청</li></ul><h2>온라인 문의폼을 제공하지 않는 이유</h2><p>현재 GitHub Pages 정적 호스팅만으로는 서버 측 유효성 검사, 요청 빈도 제한과 저장 성공 확인을 갖춘 안전한 문의처리를 보장하기 어렵습니다. 저장되지 않는 문의를 성공한 것처럼 표시하지 않기 위해 온라인 폼 대신 전화와 이메일을 제공합니다.</p></section></div></section>`;
await emit("/contact/", layout({ title: "문의", description: `한지붕 전화 ${site.phone}, 이메일 ${site.email}과 문의 시 필요한 최소정보를 안내합니다.`, path: "/contact/", body: contactBody, breadcrumbs: [{ label: "문의", href: "/contact/" }] }));

const privacyBody = `${pageHero({ eyebrow: "개인정보 처리방침", title: "필요한 정보만 받고,<br>처리방식을 분명히 알립니다.", description: "한지붕 웹사이트와 전화·이메일 문의 과정에서의 개인정보 처리 원칙입니다.", meta: `<div class="page-meta"><span>시행일 2026년 9월 23일</span><span>마지막 수정일 2026년 9월 23일</span></div>` })}<section class="section"><div class="container content-layout"><article class="prose"><h2>1. 현재 웹사이트에서 수집하는 정보</h2><p>현재 웹사이트에는 온라인 문의폼, 회원가입, 결제, 분석도구와 광고 추적기능이 없습니다. 페이지를 읽는 것만으로 한지붕이 이름·연락처를 직접 수집하지 않습니다.</p><h2>2. 전화·이메일 문의 시 처리하는 정보</h2><p>이용자가 전화나 이메일로 자발적으로 문의하는 경우 이름, 연락 가능한 전화번호 또는 이메일, 시·군·구 수준의 지역, 문의유형, 문의내용과 선택적으로 선호 연락시간을 처리할 수 있습니다. 초기 문의에서 주민등록번호, 신분증, 계좌번호, 상세주소, 집 사진, 가족의 실명과 연락처, 건강정보, 범죄경력, 재산정보, 종교와 정치성향을 요구하지 않습니다.</p><h2>3. 처리 목적</h2><p>문의 확인, 답변, 상담·봉사·기관협력 가능성 검토와 이용자의 개인정보 관련 요청에 대응하기 위해 사용합니다. 상담 문의만으로 계약이나 유료서비스 이용이 확정되지 않습니다.</p><h2>4. 보유기간</h2><p>전화·이메일 문의정보의 구체적인 보유기간은 현재 운영기준 확인이 필요합니다. 한지붕은 보유기간을 확정하기 전 불필요한 정보를 추가로 수집하지 않으며, 문의 접수 시 필요한 경우 처리와 보유범위를 안내합니다. 법령에 따른 보존의무가 확인되는 경우 해당 기간을 따릅니다.</p><h2>5. 파기방법</h2><p>보유 목적이 끝나고 별도의 보존 의무가 없으며 내부 보유기준에 따른 기간이 지난 정보는 복구하기 어려운 방법으로 삭제하거나 종이 문서를 분쇄합니다.</p><h2>6. 제3자 제공과 외부 영리사업자</h2><p>현재 웹사이트는 문의정보를 외부 영리서비스나 고객관리시스템으로 자동 전송하지 않습니다. 제3자에게 제공할 필요가 생기는 경우 제공받는 자, 목적, 항목과 보유기간을 알리고 관련 법령에 따른 동의를 확인해야 합니다.</p><h2>7. 처리위탁과 외부 서비스</h2><p>웹사이트는 GitHub Pages에서 제공되며, 이메일 문의는 Google의 Gmail 서비스를 통해 전달됩니다. 한지붕은 별도의 분석도구, 광고 네트워크와 온라인 폼 서비스를 사용하지 않습니다. 호스팅·이메일 서비스 제공자의 정보 처리는 각 서비스 정책의 적용을 받을 수 있습니다.</p><h2>8. 이용자의 권리</h2><p>이용자는 한지붕이 보유한 자신의 개인정보에 대해 열람, 정정, 삭제와 처리정지를 요청할 수 있습니다. 본인 확인에 필요한 최소정보를 확인할 수 있으며, 다른 사람의 권리를 침해하거나 법령상 제한이 있는 경우에는 사유를 안내합니다.</p><h2>9. 안전조치</h2><p>공개 사이트에 회원명부, 원본 회의록의 개인정보, 서명, 계좌번호와 민감서류를 게시하지 않습니다. 문의정보는 공개 저장소에 기록하지 않으며, 필요한 담당자만 확인하도록 관리해야 합니다.</p><h2>10. 개인정보 문의</h2><p>대표자 김현수 · 전화 <a href="${site.phoneHref}">${site.phone}</a> · 이메일 <a href="${site.emailHref}">${site.email}</a></p><h2>11. 변경이력</h2><p>2026년 9월 23일: 온라인 문의폼과 분석도구를 사용하지 않는 현재 사이트 구조에 맞추어 최초 시행했습니다.</p></article><aside class="side-nav"><h2>안내</h2><a href="/contact/">개인정보 문의</a><a href="/terms/">사이트 이용안내</a><a href="/transparency/">운영·투명성</a></aside></div></section>`;
await emit("/privacy/", layout({ title: "개인정보 처리방침", description: "한지붕 웹사이트와 전화·이메일 문의 과정의 개인정보 처리항목, 목적과 이용자 권리를 안내합니다.", path: "/privacy/", body: privacyBody, breadcrumbs: [{ label: "개인정보 처리방침", href: "/privacy/" }] }));

const termsBody = `${pageHero({ eyebrow: "사이트 및 프로그램 이용안내", title: "한지붕 정보의 범위와<br>이용 원칙을 안내합니다.", description: "공익자료와 상담을 이용하기 전에 서비스의 성격, 책임범위와 금지행위를 확인해 주세요.", meta: updatedMeta })}<section class="section"><div class="container content-layout"><article class="prose"><h2>1. 사이트의 목적</h2><p>한지붕 웹사이트는 어르신 주택 개선 무료상담, 세대교류 봉사 프로그램, 주거상생 실태조사와 관련 공익자료를 제공하기 위해 운영합니다.</p><h2>2. 공익자료의 범위</h2><p>사이트의 자료는 생활 전 확인할 일반 정보와 대화 도구입니다. 개별 주택에 대한 건축·전기·가스·소방 진단, 부동산 중개, 계약대행, 법률·세무 자문을 대신하지 않습니다.</p><h2>3. 무료상담</h2><p>기초상담은 무료이며 상담 신청만으로 공간 제공, 입주, 계약 또는 유료서비스 이용이 확정되지 않습니다. 이용자는 상담 후에도 진행하지 않거나 참여를 중단할 수 있습니다.</p><h2>4. 정확한 정보 제공</h2><p>문의자는 다른 사람의 개인정보를 권한 없이 제공하지 않아야 하며, 상담과 참여에 필요한 범위에서 사실에 맞는 정보를 알려야 합니다. 초기 문의에 주민등록번호, 신분증, 계좌번호와 상세주소를 보내지 마세요.</p><h2>5. 지식재산과 인용</h2><p>한지붕이 작성한 자료는 출처와 제목, 주소를 표시하여 비영리 교육 목적으로 인용할 수 있습니다. 문맥을 왜곡하거나 상업적 상품의 보증자료로 사용하는 것은 허용하지 않습니다.</p><h2>6. 외부기관 확인</h2><p>거주 형태, 계약, 전입신고, 세금과 법적 권리·의무는 개별 상황에 따라 달라질 수 있으므로 주민센터, 법률·세무 전문가 또는 관계기관에 별도로 확인해야 합니다.</p><h2>7. 이용 제한</h2><p>타인의 개인정보 침해, 허위정보 제출, 사기·폭력·차별·영업 목적 이용, 사이트의 정상적인 운영을 방해하는 행위는 제한될 수 있습니다.</p><h2>8. 문의</h2><p>이용안내와 프로그램 범위에 관한 문의는 전화 <a href="${site.phoneHref}">${site.phone}</a> 또는 이메일 <a href="${site.emailHref}">${site.email}</a>로 보내 주세요.</p></article><aside class="side-nav"><h2>관련 안내</h2><a href="/privacy/">개인정보 처리방침</a><a href="/programs/">공익사업</a><a href="/contact/">문의</a></aside></div></section>`;
await emit("/terms/", layout({ title: "사이트 및 프로그램 이용안내", description: "한지붕 공익자료와 무료상담의 성격, 책임범위, 개인정보와 이용 원칙을 안내합니다.", path: "/terms/", body: termsBody, breadcrumbs: [{ label: "이용안내", href: "/terms/" }] }));

function noFormPage(kind, pathValue) {
  return layout({ title: `${kind} 문의 안내`, description: `현재 ${kind} 문의는 전화와 이메일로 받고 있습니다.`, path: pathValue, robots: "noindex,nofollow", body: `<section class="status-page"><div class="container narrow"><p class="eyebrow">온라인 접수 안내</p><h1>확인되지 않은 접수 완료를<br>표시하지 않습니다.</h1><p>현재 사이트에는 안전하게 검증된 온라인 문의 저장기능이 없습니다. ${kind} 문의는 전화 ${site.phone} 또는 이메일 ${site.email}로 보내 주세요.</p><div class="hero-actions"><a class="button" href="${site.phoneHref}">전화 문의</a><a class="button button-secondary" href="${site.emailHref}">이메일 문의</a><a class="button button-text" href="/contact/">문의 방법 보기</a></div></div></section>`, breadcrumbs: [{ label: `${kind} 문의 안내`, href: pathValue }] });
}
await emit("/thanks/consultation/", noFormPage("무료상담", "/thanks/consultation/"), { indexable: false });
await emit("/thanks/partnership/", noFormPage("기관협력", "/thanks/partnership/"), { indexable: false });

const notFoundBody = `<section class="status-page"><div class="container narrow"><p class="eyebrow">요청한 페이지를 찾을 수 없습니다</p><h1>404</h1><p>한지붕 사이트는 주거상생 공익사업 중심으로 개편되었습니다. 주소를 다시 확인하거나 아래 메뉴에서 필요한 정보를 찾아 주세요.</p><div class="hero-actions"><a class="button" href="/">홈으로 가기</a><a class="button button-secondary" href="/resources/">주거상생 자료 보기</a><a class="button button-text" href="/contact/">문의</a></div></div></section>`;
const notFoundHtml = layout({ title: "페이지를 찾을 수 없습니다", description: "요청한 페이지를 찾을 수 없습니다.", path: "/404/", robots: "noindex,nofollow", body: notFoundBody });
await emit("/404/", notFoundHtml, { indexable: false });
await emit("/404.html", notFoundHtml, { indexable: false });

const sitemapEntries = generated.filter((page) => page.indexable && page.route !== "/404.html");
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapEntries.map((page) => `  <url><loc>${absolute(page.route)}</loc><lastmod>${page.updatedAt}</lastmod></url>`).join("\n")}\n</urlset>\n`;
await writeFile(path.join(out, "sitemap.xml"), sitemap, "utf8");
await writeFile(path.join(out, "robots.txt"), `User-agent: *\nAllow: /\nDisallow: /thanks/\nDisallow: /api/\nDisallow: /admin/\nDisallow: /src/\nDisallow: /scripts/\nDisallow: /tests/\nDisallow: /README.md\nDisallow: /AD_GRANTS_READINESS.md\nDisallow: /CONTENT_SOURCES.md\nDisallow: /CONTENT_GAPS.md\nDisallow: /DEPLOYMENT.md\nDisallow: /POST_DEPLOY_CHECKLIST.md\nSitemap: ${site.url}/sitemap.xml\n`, "utf8");
await writeFile(path.join(out, "site.webmanifest"), JSON.stringify({ name: "비영리단체 한지붕", short_name: site.name, start_url: "/", display: "standalone", background_color: "#f7f4ec", theme_color: "#183f36", icons: [{ src: "/assets/favicon.svg", sizes: "any", type: "image/svg+xml" }] }, null, 2), "utf8");
await writeFile(path.join(out, "CNAME"), "hanjibung.kr\n", "utf8");
await writeFile(path.join(out, ".nojekyll"), "", "utf8");
await mkdir(path.join(out, "assets"), { recursive: true });
await cp(path.join(root, "src", "assets", "site.css"), path.join(out, "assets", "site.css"));
await cp(path.join(root, "src", "assets", "site.js"), path.join(out, "assets", "site.js"));
await cp(path.join(root, "src", "assets", "favicon.svg"), path.join(out, "assets", "favicon.svg"));

const ogSource = path.join(root, "src", "assets", "og-default.png");
try {
  await cp(ogSource, path.join(out, "assets", "og-default.png"));
} catch {
  throw new Error("src/assets/og-default.png 파일이 필요합니다. npm run build 전에 OG 이미지를 생성해 주세요.");
}

await writeFile(path.join(out, "build-manifest.json"), JSON.stringify({ generatedAt: new Date().toISOString(), pages: generated.map(({ route, indexable, updatedAt }) => ({ route, indexable, updatedAt })) }, null, 2), "utf8");
console.log(`Built ${generated.length} HTML files and ${sitemapEntries.length} indexable routes.`);
